{% set name = "ds9" %}
{% set version = "8.7b3" %}
{% set number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ds9.si.edu/download/source/ds9.{{ version }}.tar.gz
  sha256: f1713cd052ef21c5a5c89150deeb2196218a85422c9ff4955c3ae9238de22594
  #~ git_url: https://github.com/SAOImageDS9/SAOImageDS9
  #~ git_branch: master
  #~ git_url: https://github.com/kglotfelty/SAOImageDS9
  #~ git_branch: conda_for_ciao

build:
  number: {{ number }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - libclang-cpp  # [osx]
    - make
    - autoconf
    - automake
    - m4
    - pkg-config
    - bison
    - flex

  host:
    # The host requirements are longer than expected to get Tk to
    # build with support for true-type fonts (look for 'xft' enable
    # in configure output).
    - bzip2
    - expat
    - fontconfig
    - libfreetype
    - libiconv
    - libpng
    - libxml2-devel
    - libxslt
    - libuuid
    - icu >=75.1, <76.0a0
    - zlib
    - xorg-kbproto
    - xorg-libx11
    - xorg-libXft
    - xorg-libxrender
    - xorg-renderproto
    - xorg-xorgproto
    - xorg-xproto

  run:
    - xorg-libxft
    - icu

about:
  home: https://ds9.si.edu
  license: GPL-3.0-only
  license_family: GPL
  summary: Astronomical image display and analysis application
  dev_url: https://github.com/SAOImageDS9/SAOImageDS9
  description: |
      SAOImageDS9 is an astronomical imaging and data visualization
      application.  DS9 supports FITS images and binary tables,
      multiple frame buffers, region manipulation, and many
      scale algorithms and colormaps.  It provides for easy
      communication with external analysis tasks and is highly
      configurable and extensible via XPA and SAMP.

extra:
  recipe-maintainers:
    - kglotfelty
