{% set name = "ds9" %}
{% set version = "8.7.b3" %}
{% set number = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/SAOImageDS9/SAOImageDS9
  #~ git_url: https://github.com/kglotfelty/SAOImageDS9
  #~ git_branch: conda_for_ciao
  git_branch: master

build:
  number: {{ number }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - make
    - autoconf
    - automake
    - m4
    - pkg-config
    - bison
    - flex

  host:
    # The host requirements are longer than expected to get Tk to
    # build with support for true-type fonts (look for 'xft' enable
    # in configure output).
    - bzip2
    - expat
    - fontconfig
    - libfreetype
    - libiconv
    - libpng
    - libxml2-devel
    - libxslt
    - libuuid
    - zlib
    - xorg-kbproto
    - xorg-libx11
    - xorg-libXft
    - xorg-libxrender
    - xorg-renderproto
    - xorg-xorgproto
    - xorg-xproto

  run:
    - font-ttf-dejavu-sans-mono
    - font-ttf-inconsolata
    - font-ttf-source-code-pro
    - font-ttf-ubuntu
    - xorg-libxft

about:
    home: https://ds9.si.edu
    license: GPL3
    summary: O.G. Astronomical Imager
    dev_url: https://github.com/SAOImageDS9/SAOImageDS9
