{% set name = "ds9" %}
{% set version = "8.6" %}
{% set number = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/kglotfelty/SAOImageDS9
  #~ git_url: file:///lenin1.real/DS9/build_from_source/SAOImageDS9/SAOImageDS9-20251204
  git_branch: conda_for_ciao

build:
  number: {{ number }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - make
    - autoconf
    - automake
    - m4
    - pkg-config

  host:
    - bzip2
    - fontconfig
    - expat
    - libfreetype
    - libiconv
    - libpng
    - libxslt
    - libxml2-devel
    - libuuid
    - zlib
    - xorg-kbproto
    - xorg-libx11
    - xorg-libXft
    - xorg-libxrender
    - xorg-renderproto
    - xorg-xorgproto
    - xorg-xproto

  run:
    - font-ttf-dejavu-sans-mono
    - font-ttf-inconsolata
    - font-ttf-source-code-pro
    - font-ttf-ubuntu

about:
    home: https://ds9.si.edu
    license: GPL3
    summary: O.G. Astronomical Imager
